In [ ]:
## import numpy as np

def euclidean_distance(X, Y):
    X_sq_sum = np.sum(X ** 2, axis=1)
    Y_sq_sum = np.sum(Y ** 2, axis=1)
    
    Xx = np.repeat(X, Y.shape[0], axis=0)
    Yy = np.array(list(Y) * X.shape[0])
    Xs = np.repeat(X_sq_sum, Y.shape[0], axis=0)
    Ys = np.array(list(Y_sq_sum) * X.shape[0])
    
    print(Xx + Yy - 2 * np.array([np.dot(X[i], Y[j])
                     for i in range(X.shape[0]) for j in range(Y.shape[0])]*3).reshape(X.shape[0]*3, Y.shape[0]))
    
    print(np.array([X[i] + Y[j]
                     for i in range(X.shape[0]) for j in range(Y.shape[0])]))
    
    return np.sqrt(np.array([X_sq_sum[i] + Y_sq_sum[j] - 2 * np.dot(X[i], Y[j])
                     for i in range(X.shape[0]) for j in range(Y.shape[0])])).reshape(X.shape[0], Y.shape[0])


def cosine_distance(X, Y):
    X_n = np.linalg.norm(X, axis=1)
    Y_n = np.linalg.norm(Y, axis=1)
    return np.array([1 - np.dot(X[i], Y[j])/(X_n[i] * Y_n[j])
                     for i in range(X.shape[0]) for j in range(Y.shape[0])]).reshape(X.shape[0], Y.shape[0])


In [6]:
# %timeit euclidean_distance(x_new, y_new)
# %timeit scipy.spatial.distance.cdist(x_new, y_new, metric='euclidean')

print(euclidean_distance(x_new, y_new))
print(scipy.spatial.distance.cdist(x_new, y_new, metric='euclidean'))

[[-48 -10  -8]
 [-62 -13 -14]
 [-52 -11 -12]
 [-58 -12  -9]
 [-52 -11 -11]
 [-62 -13 -13]]
[[4 6 8]
 [0 5 4]
 [0 5 4]
 [4 6 9]
 [0 5 5]
 [0 5 5]]
[[3.46410162 3.         3.        ]
 [3.         3.74165739 3.74165739]]
[[3.46410162 3.         3.        ]
 [3.         3.74165739 3.74165739]]


In [42]:
def f(x, y):
    print(x.reshape(1, -1), y.reshape(1, -1))
    print(((x.reshape(1, -1) - y.reshape(-1, 1)).reshape(x.shape[1], -1).sum(axis=0)))
    
    print(np.array([((x[i] - y[j])**2).sum() for i in range(x.shape[0]) for j in range(y.shape[0])]).reshape(x.shape[0], y.shape[0]))

f(x_new, y_new)

[[1 2 3 1 2 4]] [[ 3  4  5 -1  3  1 -1  3  1]]
[ 2  5  8  2  5 11 -7 -4 -1 -7 -4  2 -4 -1  2 -4 -1  5]
[[12  9  9]
 [ 9 14 14]]


In [13]:
%timeit cosine_distance(x_new, y_new)
%timeit scipy.spatial.distance.cdist(x_new, y_new, metric='cosine')
print(cosine_distance(x_new, y_new))
print(scipy.spatial.distance.cdist(x_new, y_new, metric='cosine'))

210 µs ± 28 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
49.1 µs ± 5.76 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
[[0.01729237 0.35534163 0.35534163]
 [0.04331923 0.40784347 0.40784347]]
[[0.01729237 0.35534163 0.35534163]
 [0.04331923 0.40784347 0.40784347]]


In [5]:
import scipy.spatial.distance

In [3]:
X = np.array([[1, 2, 3], [1, 2, 4]])
Y = np.array([[3, 4, 5], [-1, 3, 1], [-1, 3, 1]])
x_new = X
y_new = Y
# if X.shape[0] < Y.shape[0]:
#     x_new = np.zeros_like(Y)
#     x_new[:X.shape[0]] += X[:X.shape[0]]
# elif X.shape[0] > Y.shape[0]:
#     y_new = np.zeros_like(X)
#     y_new[:Y.shape[0]] += Y[:Y.shape[0]]


In [43]:
print(X)

[[1 2 3]
 [1 2 4]]


In [44]:
print(X.sum(axis=0))

[2 4 7]
