## Задание


Реализуйте класс разреженной матрицы `CooSparseMatrix` с координатным форматом хранения. В памяти должны хранится только ненулевые элементы матрицы!

1. Метод `__init__` класса принимает два аргумента:

* ijx_list — список кортежей (i, j, x), i,j - положение элемента в матрице, x - значение элемента.
* shape — кортеж из двух элементов, размер матрицы

  Если в списке встречаются одинаковые индексы, необходимо выбросить исключение TypeError

2. Необходимо реализовать простую индексацию матриц. При вызове matrix[i] необходимо вернуть объект `CooSparseMatrix`, соответствующий i-ой строки исходной матрице и имеющий размер 1 на количество столбцов в матрице. При вызове matrix[i, j] необходимо вернуть [i, j] элемент матрицы. Также реализуйте возможность присвоить [i,j] элементу матрицы вещественное число.

   *Замечание. Также рекомендуется реализовать для себя функцию или метод to_array, преобразующий разреженную матрицу в numpy ndarray.*
   

3. Добавьте в класс `CooSparseMatrix` возможность сложения и вычитания матриц, а также умножения матриц на число. При сложнение и вычитании матриц разного размера должно выбрасываться исключение `TypeError`.


4. Добавьте в класс `CooSparseMatrix` следующие атрибуты:

    4.1. Атрибут `shape`, задающий размер массива

    Значение атрибута — кортеж из двух целых положительных чисел. При попытке присвоить атрибуту что-либо другое, должно выбрасываться исключение `TypeError`. При попытке присвоить атрибуту размер, не соответствующий существующему (например, попытаться сменить размер матрицы с (2, 5) на (3, 4)) должно выбрасываться исключение `TypeError`. При корректном присваивании, необходимо изменить размер матрицы согласно C-order.

    4.2. Атрибут `T`, возвращающий транспонированную матрицу. При попытке присвоить что-либо атрибуту должно выбрасываться исключение `AttributeError`. Обращение к атрибуту не должно влиять на исходную матрицу!


## Краткие теоретические сведения

Разреженная матрица — матрица с преимущественно нулевыми элементами. В противном случае, если бо́льшая часть элементов матрицы ненулевые, матрица считается плотной.

### Форматы хранения разреженной матрицы

Существует несколько способов хранения (представления) разреженных матриц, отличающиеся:

удобством изменения структуры матрицы (активно используется косвенная адресация) - это структуры в виде списков и словарей.
скоростью доступа к элементам и возможной оптимизацией матричных вычислений (чаще используются плотные блоки - массивы, увеличивая локальность доступа к памяти).

* **Словарь по ключам (DOK - Dictionary of Keys)** строится как словарь, где ключ это пара (строка, столбец), а значение это соответствующий строке и столбцу элемент матрицы.

* **Список списков (LIL - List of Lists)** строится как список строк, где строка это список узлов вида (столбец, значение).

* **Список координат (COO - Coordinate list)** хранится список из элементов вида (строка, столбец, значение).


#### Сжатое хранение строкой (CSR - compressed sparse row, CRS - compressed row storage, Йельский формат)

Мы представляем исходную матрицу $M^{n\times m}$, cодержащую $N_{NZ}$ ненулевых значений в виде трёх массивов:

* массив значений - массив размера $N_{NZ}$, в котором хранятся ненулевые значения взятые подряд из первой непустой строки, затем идут значения из следующей непустой строки и т.д.
* массив индексов столбцов - массив размера $N_{NZ}$ и хранит номера столбцов, соответствующих элементов из массива значений.
* массив индексации строк - массив размера $n+1$ (кол_во_строк + 1), для индекса $i$ хранит количество ненулевых элементов в строках до $i-1$ включительно, стоит отметить что последний элемент массива индексации строк совпадает с $N_{NZ}$, а первый всегда равен $0$.

Примеры:

Пусть $M={\begin{pmatrix}1&2&0\\0&4&0\\0&2&6\end{pmatrix}}$, тогда

массив_значений          = {1, 2, 4, 2, 6}

массив_индексов_столбцов = {0, 1, 1, 1, 2}

массив_индексации_строк  = {0, 2, 3, 5} -- в начале хранится 0, как запирающий элемент

Пусть $M={\begin{pmatrix}1&2&0&3\\0&0&4&0\\0&1&0&11\end{pmatrix}}$, тогда

массив_значений          = {1, 2, 3, 4, 1, 11}

массив_индексов_столбцов = {0, 1, 3, 2, 1,  3}

массив_индексации_строк  = {0, 3, 4, 6} -- в начале хранится 0, как запирающий элемент

Для того, чтобы восстановить исходную матрицу нужно взять некоторое значение $v$ в первом массиве и соответствующий индекс $i_{v}:Arr_{values}[i_{v}]=v$, тогда номер столбца $n_{c}=Arr_{cols}[i_{v}]$, а номер строки $n_{r}$ находится, как наименьшее $n_{r}$, для которого $Arr_{rows}[n_{r}+1]\geq i_{v}+1$.

#### Сжатое хранение столбцом(CSС - compressed sparse column, CСS - compressed column storage)

То же самое что и CRS, только строки и столбцы меняются ролями - значения храним по столбцам, по второму массиву можем определить строку, после подсчётов с третьим массивом - узнаём столбцы.

## Результаты выполнения работы

Реализован класс разреженных матриц CooSparseMatrix с форматом хранения данных в виде списка координат.

Класс содержит следующие методы: 
- **\_\_init__(self, ijx_list, shape, antirec=True)** - инициализация класса. 
    - ijx_list - список кортежей (i, j, x), i,j - положение элемента в матрице, x - значение элемента
    - shape - кортеж из двух элементов, размер матрицы
    - antirec - вспомогательный аргумент, используемый для избегания зацикливания)
- **\_\_getitem__(self, index)** - получение значения по индексу
    - index - индекс элемента. Если index - число, то возвращается строка матрицы под номером index в виде разреженной матрицы CooSparseMatrix размером (1, self.shape[1]). Если index - кортеж, возвращается значение матрицы, находящееся по указанному индексу.
- **\_\_setitem__(self, key, value)** - установка значения по индексу
    - key - кортеж из двух элементов, положение элемента в матрице (индекс)
    - value - значение
- **\_\_add__(self, other)** - прибавление матрицы
    - other - прибавляемая матрица
- **\_\_sub__(self, other)** - вычитание матрицы
    - other - вычитаемая матрица
- **\_\_mul__(self, other)** - умножение на число
    - other - скаляр, на который происходит умножение

Атрибуты класса:
- **T** - транспонированная матрица
- **shape** - размер матрицы

In [1]:

class CooSparseMatrix:

    def __init__(self, ijx_list, shape, antirec=True):
        self.ijx_dict = {}
        for i, j, x in ijx_list:
            if (i, j) in self.ijx_dict:
                raise TypeError
            if (type(i) != int) or (type(j) != int):
                raise TypeError
            elif x != 0:
                self.ijx_dict[(i, j)] = x
        if ((type(shape) != tuple) or (len(shape) != 2) or
                (type(shape[0]) != int) or (type(shape[1]) != int)):
            raise TypeError
        self.shape = shape
        if antirec:
            self.T = CooSparseMatrix([(key[1], key[0], self[key])
                                     for key in list(self.ijx_dict.keys())],
                                     (self.shape[1], self.shape[0]),
                                     antirec=False)


    def __getitem__(self, index):
        if type(index) == int:
            if index >= self.shape[0]:
                raise TypeError
            my_mtr = []
            my_str = ()
            for j in range(self.shape[1]):
                if ((index, j) in self.ijx_dict):
                    my_str = (index, j, self.ijx_dict[(index, j)])
                else:
                    my_str = (index, j, 0)
                my_mtr.append(my_str)
            return CooSparseMatrix(ijx_list=my_mtr, shape=(1, self.shape[1]))

        elif type(index) == tuple:
            if (index[0] >= self.shape[0]) or (index[1] >= self.shape[1]):
                raise TypeError
            if (index[0], index[1]) in self.ijx_dict:
                return self.ijx_dict[index[0], index[1]]
            else:
                return 0

        else:
            raise TypeError

    def __setitem__(self, key, value):
        if value != 0:
            self.ijx_dict[key] = value
            self.T.ijx_dict[(key[1], key[0])] = value
        elif key in self.ijx_dict:
            del self.ijx_dict[key]

    def __add__(self, other):
        if self.shape != other.shape:
            raise TypeError
        else:
            return CooSparseMatrix([key + (self[key] + other[key],) for key
                                    in set(list(self.ijx_dict.keys()) +
                                           list(other.ijx_dict.keys()))],
                                   self.shape)

    def __sub__(self, other):
        if self.shape != other.shape:
            raise TypeError
        else:
            return CooSparseMatrix([key + (self[key] - other[key],) for key
                                    in set(list(self.ijx_dict.keys()) +
                                           list(other.ijx_dict.keys()))],
                                   self.shape)

    def __mul__(self, other):
        if type(other) != int:
            raise TypeError
        else:
            return CooSparseMatrix([key + (self[key]*other,) for key
                                    in list(self.ijx_dict.keys())], self.shape)

    def __setattr__(self, name, value):
        if name == 'T':
            if 'T' in self.__dict__:
                raise AttributeError
        if name == 'shape':
            if 'shape' in self.__dict__:
                if ((type(value) != tuple) or (len(value) != 2) or
                        (type(value[0]) != int) or (type(value[1]) != int)):
                    raise TypeError
                if (value[0] * value[1]) != (self.shape[0] * self.shape[1]):
                    raise TypeError
                else:
                    new_dict = {}
                    for key in list(self.ijx_dict.keys()):
                        new_dict[divmod(key[0] * self.shape[1] + key[1],
                                        value[1])] = self.ijx_dict[key]
                    self.ijx_dict = new_dict.copy()
                    self.__dict__[name] = value

                    for key in list(self.ijx_dict.keys()):
                        self.T.ijx_dict[(key[1], key[0])] = self[key]
                        
            else:
                self.__dict__[name] = value
        else:
            self.__dict__[name] = value


Также реализована функция to_array, преобразующий разреженную матрицу в numpy ndarray.

In [2]:
import numpy as np

def to_array(mtr):
    ar = np.zeros(mtr.shape)
    for k, v in mtr.ijx_dict.items():
        ar[k] = v
    return ar

### Примеры работы с классом CooSparseMatrix

In [3]:
matrix = CooSparseMatrix(ijx_list=[(0, 0, 1), (1, 0, 2)], shape=(2, 2))

In [4]:
# получение значения 

matrix1 = CooSparseMatrix(ijx_list=[(0, 0, 1), (1, 0, 2)], shape=(2, 2))
matrix1[0, 0]

# 1

1

In [5]:
# установка значения

matrix1[1, 1] = 2
matrix1[1, 1]

# 2

2

In [6]:
# преобразование к numpy.ndarray

matrix = CooSparseMatrix(ijx_list=[(0, 0, 1), (1, 0, 2)], shape=(2, 2))
to_array(matrix)

# array([[1., 0.], [2., 0.]])

array([[1., 0.],
       [2., 0.]])

In [7]:
# сложение

matrix1 = CooSparseMatrix(ijx_list=[(0, 0, 1), (1, 0, 2)], shape=(2, 2))
matrix2 = CooSparseMatrix(ijx_list=[(0, 1, 2), (1, 0, 1)], shape=(2, 2))
matrix3 = matrix1 + matrix2

to_array(matrix3)

# array([[1., 2.], [3., 0.]])

array([[1., 2.],
       [3., 0.]])

In [8]:
# сложение матриц разного размера

matrix1 = CooSparseMatrix(ijx_list=[(0, 0, 1), (1, 0, 2)], shape=(2, 2))
matrix2 = CooSparseMatrix(ijx_list=[(0, 1, 2), (1, 0, 1)], shape=(2, 3))
matrix3 = matrix1 + matrix2

to_array(matrix3)

# TypeError

TypeError: 

In [9]:
# умножение

to_array(matrix1 * 5)

# array([[ 5., 0.], [10., 0.]])

array([[ 5.,  0.],
       [10.,  0.]])

In [10]:
# получение размера

matrix = CooSparseMatrix(ijx_list=[(0, 0, 1), (1, 1, 2), (2, 3, 5), (1, 3, 0)], shape=(3, 5))
matrix.shape

# (3, 5)

(3, 5)

In [11]:
# изменение размера

matrix.shape = (5, 3)
to_array(matrix)

# array([[1., 0., 0.], [0., 0., 0.],
# [2., 0., 0.], [0., 0., 0.],
# [0., 5., 0.]
# )

array([[1., 0., 0.],
       [0., 0., 0.],
       [2., 0., 0.],
       [0., 0., 0.],
       [0., 5., 0.]])

In [12]:
# изменение размера, попытка присвоить атрибуту размер, не соответствующий существующему

matrix.shape = (5, 4)
to_array(matrix)

# TypeError

TypeError: 

In [13]:
# получение транспонированной матрицы

matrix = CooSparseMatrix(ijx_list=[(0, 0, 1), (1, 1, 2), (2, 3, 5), (1, 3, 0)], shape=(3, 5))
to_array(matrix.T)

# array([[1., 0., 0.], [0., 2., 0.],
# [0., 0., 0.], [0., 0., 5.],
# [0., 0., 0.]
# )

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 0.],
       [0., 0., 5.],
       [0., 0., 0.]])

In [14]:
# попытка присвоить что-либо атрибуту T

matrix.T = matrix * 2

# AttributeError  

AttributeError: 

### Assert проверки правильности работы

In [15]:
matrix1 = CooSparseMatrix([], shape=(100, 100))

for i in range(100):
    for j in range(100):
        if i % 13 == 0:
            matrix1[i, j] = i - 2 * (j ** 2)
        if j % 11 == 0:
            matrix1[i, j] = j + 3 * (i ** 3)

matrix2 = matrix1.T

In [16]:
# соответствие размеров прямой и транспонированной матрицы

assert(matrix2.shape == matrix1.shape[::-1])

In [17]:
# соответствие значений прямой и транспонированной матрицы

for i in range(matrix2.shape[0]):
    for j in range(matrix2.shape[1]):
        assert(matrix2[i, j] == matrix1[j, i])

In [18]:
# правильность умножения

matrix3 = matrix1 * 2

for i in range(matrix1.shape[0]):
    for j in range(matrix1.shape[1]):
        assert(matrix1[i, j] * 2 == matrix3[i, j])