Написать функцию replace_nan_to_means(X), принимающую матрицу X. Функция должна вернуть копию матрицы X, в которой все значения nan в каждом столбце заменены на среднее арифметическое остальных элементов столбца. В случае столбца из одних nan необходимо заменить все элементы столбца на нули. Исходная матрица X должна остаться неизменной!

Формат ввода
replace_nan_to_means(np.array([ [0, 1, 2], [np.nan, 1, np.nan], [5, 6, 7] ])

Формат вывода
np.array([ [0, 1, 2], [2.5, 1, 4.5], [5, 6, 7] ])

In [1]:
import numpy as np


def replace_nan_to_means(x):
    mask = np.isnan(x)
    x_without_nan = x.copy()
    mask2 = np.all(mask, axis=0)
    np.transpose(x_without_nan)[mask2] = 0
    x_without_nan[mask] = np.nanmean(x_without_nan, axis = 0)[np.where(mask)[1]]
    return x_without_nan


print(replace_nan_to_means(np.array([ [0, 1, np.nan], [np.nan, 1, np.nan], [5, 6, np.nan] ])))


[[0.  1.  0. ]
 [2.5 1.  0. ]
 [5.  6.  0. ]]


In [2]:
np.array([ [0, 1, 2], [np.nan, 1, np.nan], [np.nan, 6, 7] ])

array([[ 0.,  1.,  2.],
       [nan,  1., nan],
       [nan,  6.,  7.]])

In [23]:
print(replace_nan_to_means(np.array([ [0, 1, 2], [np.nan, 1, np.nan], [np.nan, 6, 7] ])))

(array([nan, nan, nan]), array([0.        , 2.66666667, 4.5       ]))


In [25]:
print(replace_nan_to_means(np.array([ [0, 1, 2], [np.nan, 1, np.nan], [np.nan, 6, 7] ])))

(array([1, 1, 2], dtype=int64), array([0, 2, 0], dtype=int64))
