In [1]:
import numpy as np


class RleSequence:

    def __init__(self, input_sequence):

        if input_sequence.size == 0:
            raise TypeError
        self.values = \
            np.hstack((input_sequence[np.hstack((np.diff(input_sequence) != 0,
                                                 [False]))],
                       input_sequence[-1]))
        self.repeat = \
            np.hstack(((np.where(np.hstack((np.diff(input_sequence) != 0,
                                            [False]))))[0],
                       input_sequence.size - 1))\
            - np.hstack(([-1],
                         (np.where(np.hstack((np.diff(input_sequence) != 0,
                                              [False]))))[0]))

    def __getitem__(self, i):
        cums = np.cumsum(self.repeat)
        if type(i) == slice:
            return(np.array([self.values[sum(cums <= j)]
                             for j in range(0 if i.start is None
                                            else sum(self.repeat) + i.start
                                            if i.start < 0
                                            else sum(self.repeat)
                                            if i.start > sum(self.repeat)
                                            else i.start,
                                            sum(self.repeat) if i.stop is None
                                            else sum(self.repeat) + i.stop
                                            if i.stop < 0
                                            else sum(self.repeat)
                                            if i.stop > sum(self.repeat)
                                            else i.stop,
                                            1 if i.step is None
                                            else i.step)]))
        elif type(i) == int:
            if i < 0:
                i = sum(self.repeat) + i
            return self.values[sum(cums <= i)]
        else:
            raise TypeError

    def __contains__(self, target_elem):
        return target_elem in self.values


In [2]:
rle_seq = RleSequence(np.array([2, 2, 3, 1, 0, 2, 0, 2, 1, 0, 0, 0,
                                1, 0, 1, 2, 3, 0, 1, 2, 1, 3, 0,
                                2, 3, 2, 1, 1, 1, 0]))
print(rle_seq[1:5:])
print(rle_seq[1:20:])
print(rle_seq[4:29:])
print(rle_seq[4:7:])
print(rle_seq[17:22:])
print(rle_seq[2:2:])

[2 3 1 0]
[2 3 1 0 2 0 2 1 0 0 0 1 0 1 2 3 0 1 2]
[0 2 0 2 1 0 0 0 1 0 1 2 3 0 1 2 1 3 0 2 3 2 1 1 1]
[0 2 0]
[0 1 2 1 3]
[]


In [3]:
rle_seq = RleSequence(np.array([2, 2, 3, 1, 0, 2, 0, 2, 1, 0, 0, 0,
                                1, 0, 1, 2, 3, 0, 1, 2, 1, 3, 0,
                                2, 3, 2, 1, 1, 1, 0]))
print(rle_seq[1:5:2])
print(rle_seq[1:20:3])
print(rle_seq[4:29:3])
print(rle_seq[4:7:1])
print(rle_seq[17:22:4])
print(rle_seq[2:2:1])

[2 1]
[2 0 2 0 0 3 2]
[0 2 0 0 3 2 0 2 1]
[0 2 0]
[0 3]
[]


In [4]:
rle_seq = RleSequence(np.array([2, 2, 3, 1, 0, 2, 0, 2, 1, 0, 0, 0,
                                1, 0, 1, 2, 3, 0, 1, 2, 1, 3, 0,
                                2, 3, 2, 1, 1, 1, 0]))
print(rle_seq[1::2])
print(rle_seq[1::3])
print(rle_seq[4::3])
print(rle_seq[4::1])
print(rle_seq[17::4])
print(rle_seq[2::1])

[2 1 2 2 0 0 0 2 0 2 3 2 2 1 0]
[2 0 2 0 0 3 2 0 2 1]
[0 2 0 0 3 2 0 2 1]
[0 2 0 2 1 0 0 0 1 0 1 2 3 0 1 2 1 3 0 2 3 2 1 1 1 0]
[0 3 2 0]
[3 1 0 2 0 2 1 0 0 0 1 0 1 2 3 0 1 2 1 3 0 2 3 2 1 1 1 0]


In [5]:
tmp = np.array([0, 1, 2, 1, 2, 2, 0, 2, 0, 0, 2, 0, 2, 1, 0, 0, 2, 2, 0, 2, 0, 0, 2,
               1, 1, 1, 1, 1, 1, 0, 2, 2, 1, 0, 0, 1, 1, 2, 0, 2, 2, 0, 2, 0, 1, 2,
               1, 2, 2, 2])
rle_seq = RleSequence(tmp)

print(rle_seq[-30:45:3])
# print(rle_seq[-20], rle_seq[-15])
# for i in range(-20, 39, 5):
#     print(i)
print(rle_seq[-20:39:5])
print(rle_seq[-20:-19:5])
print(rle_seq[-36:-17:2])
print(rle_seq[-36:-1:2])
print(rle_seq[-4::2])
print(rle_seq[:-40:2])

[0 1 1 0 1 1 0 0 1]
[2 1]
[2]
[0 2 0 0 2 1 1 1 2 1]
[0 2 0 0 2 1 1 1 2 1 0 1 0 2 2 1 1 2]
[1 2]
[0 2 2 0 0]


In [6]:
tmp = np.array([2, 0, 2, 1, 2, 1, 1, 0, 1, 0, 0, 2, 2, 2, 0, 1, 2, 2, 1, 0, 0, 2, 2,
                0, 0, 0, 1, 2, 0, 2])

rle_seq = RleSequence(tmp)

print(tmp[-30:15:])
print(tmp[-24:35:])
print(tmp[-24:-19:2])
print(tmp[-30:-11:2])

print(rle_seq[-30:15:])
print(rle_seq[-24:35:])
print(rle_seq[-24:-19:2])
print(rle_seq[-30:-11:2])



[2 0 2 1 2 1 1 0 1 0 0 2 2 2 0]
[1 0 1 0 0 2 2 2 0 1 2 2 1 0 0 2 2 0 0 0 1 2 0 2]
[1 1 0]
[2 2 2 1 1 0 2 0 2 1]
[2 0 2 1 2 1 1 0 1 0 0 2 2 2 0]
[1 0 1 0 0 2 2 2 0 1 2 2 1 0 0 2 2 0 0 0 1 2 0 2]
[1 1 0]
[2 2 2 1 1 0 2 0 2 1]


In [7]:
tmp.size

30

In [ ]:
%time
np.random.seed(153)
tmp_array = np.random.randint(0, 3, 10 ** 6)

rle_seq = RleSequence(tmp_array)

sum_elements = 0
for elem in rle_seq:
    sum_elements += elem
print(sum_elements)

Wall time: 0 ns


In [ ]:
%%timeit
rle_seq[3:9:]