In [37]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
%matplotlib inline

**Задание 3.**

Изучите теоретический материал по теме «Множественная линейная регрессия».
Рассмотрите примеры решения задачи в пакете R.

**Задание 4.**

Ознакомьтесь с материалами:
- ЛЗ_2_Ввод и редактирование данных с помощью редактора данных.pdf
- ЛЗ_2_Исследование и улучшение линейной регрессионной модели.pdf
- ЛЗ_2_Предварительная обработка данных.pdf

**Задание 5.**

Решите в пакете R задачу построения и анализа уравнения множественной линейной
регрессии:

1. Подберите данные для задачи;
2. Постройте с помощью пакета R уравнение линейной регрессии (сделайте это 2мя способами:
    - по явным формулам;
    - с помощью функции lm.
3. Cравните результаты с помощью таблицы следующего вида: ...
4. Приведите в отчёте матрицу попарных корреляций и сводную информацию (summary) модели.
5. Проанализируйте степень влияния факторов на переменную отклика согласно каждой из полученных моделей;
6. Сделайте прогноз (с помощью каждой из полученных моделей. если они различны)  - на вход модели подайте не менее 10 значений из обучающей выборки и сравните:
    - истинное значение переменной отклика;
    - прогноз, полученный с помощью модели, коэффициенты которой вычислены явно;
    - прогноз, полученный с помощью модели, коэффициенты которой вычислены с помощью функции lm.
7. Проанализируйте и объясните полученные результаты.

In [28]:
from sklearn.datasets import load_diabetes
dataset = load_diabetes()
data = dataset['data']
target = dataset['target'].reshape((442, 1))
columns = dataset['feature_names']
columns.append('tg')
df = pd.DataFrame(np.hstack([data, target]), columns = columns)
df

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017282 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081414  0.083740  0.027809  0.173816   

           s4        s5        s6     tg  
0   -0.002592  0.019908 -0.017646  151.0  
1   -0.039493 -0.068330 -0.092204   75.0  
2   -0.002592  0.002864 -0.025930  141.0  
3    0.034309  0.022692 -0.009362  206.0  
4   -0.002592 -0.031991 -0.046641  135.0  
..        ...       ...       ...    ...  
437 -0.002592  0.031193  0.007207  178.0  
438  0.034309 -0.018118  0.044485  104.0  
439 -0.011080 -0.046879  0.015491  132.0  
440  0.026560  0.044528 -0.025930  220.0  
441 -0.039493 -0.004220  0.003064   57.0  

[442 rows x 11 columns]

In [36]:
X1 = np.hstack([np.ones((442, 1)), data])
T1 = X1.T
T = T1.dot(X1)
obr = np.linalg.inv(T)
Teta = obr.dot(T1).dot(target)
Teta = Teta.flatten()
print(Teta)

[ 152.13348416  -10.01219782 -239.81908937  519.83978679  324.39042769
 -792.18416163  476.74583782  101.04457032  177.06417623  751.27932109
   67.62538639]


In [141]:
data1 = sm.add_constant(data)
model = sm.OLS(target, data1).fit()

print(model.params)

[ 152.13348416  -10.01219782 -239.81908937  519.83978679  324.39042769
 -792.18416163  476.74583782  101.04457032  177.06417623  751.27932109
   67.62538639]


In [45]:
df.corr()

age       sex       bmi        bp        s1        s2        s3  \
age  1.000000  0.173737  0.185085  0.335427  0.260061  0.219243 -0.075181   
sex  0.173737  1.000000  0.088161  0.241013  0.035277  0.142637 -0.379090   
bmi  0.185085  0.088161  1.000000  0.395415  0.249777  0.261170 -0.366811   
bp   0.335427  0.241013  0.395415  1.000000  0.242470  0.185558 -0.178761   
s1   0.260061  0.035277  0.249777  0.242470  1.000000  0.896663  0.051519   
s2   0.219243  0.142637  0.261170  0.185558  0.896663  1.000000 -0.196455   
s3  -0.075181 -0.379090 -0.366811 -0.178761  0.051519 -0.196455  1.000000   
s4   0.203841  0.332115  0.413807  0.257653  0.542207  0.659817 -0.738493   
s5   0.270777  0.149918  0.446159  0.393478  0.515501  0.318353 -0.398577   
s6   0.301731  0.208133  0.388680  0.390429  0.325717  0.290600 -0.273697   
tg   0.187889  0.043062  0.586450  0.441484  0.212022  0.174054 -0.394789   

           s4        s5        s6        tg  
age  0.203841  0.270777  0.301731  0.187889  
sex  0.332115  0.149918  0.208133  0.043062  
bmi  0.413807  0.446159  0.388680  0.586450  
bp   0.257653  0.393478  0.390429  0.441484  
s1   0.542207  0.515501  0.325717  0.212022  
s2   0.659817  0.318353  0.290600  0.174054  
s3  -0.738493 -0.398577 -0.273697 -0.394789  
s4   1.000000  0.617857  0.417212  0.430453  
s5   0.617857  1.000000  0.464670  0.565883  
s6   0.417212  0.464670  1.000000  0.382483  
tg   0.430453  0.565883  0.382483  1.000000

In [46]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.518
Model:                            OLS   Adj. R-squared:                  0.507
Method:                 Least Squares   F-statistic:                     46.27
Date:                Thu, 25 Nov 2021   Prob (F-statistic):           3.83e-62
Time:                        11:28:59   Log-Likelihood:                -2386.0
No. Observations:                 442   AIC:                             4794.
Df Residuals:                     431   BIC:                             4839.
Df Model:                          10                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        152.1335      2.576     59.061      0.000     147.071     157.196
x1           -10.0122     59.749     -0.168      0.867    -127.448     107.424
x2          -239.8191     61.222     -3.917      0.000    -360.151    -119.488
x3           519.8398     66.534      7.813      0.000     389.069     650.610
x4           324.3904     65.422      4.958      0.000     195.805     452.976
x5          -792.1842    416.684     -1.901      0.058   -1611.169      26.801
x6           476.7458    339.035      1.406      0.160    -189.621    1143.113
x7           101.0446    212.533      0.475      0.635    -316.685     518.774
x8           177.0642    161.476      1.097      0.273    -140.313     494.442
x9           751.2793    171.902      4.370      0.000     413.409    1089.150
x10           67.6254     65.984      1.025      0.306     -62.065     197.316
==============================================================================
Omnibus:                        1.506   Durbin-Watson:                   2.029
Prob(Omnibus):                  0.471   Jarque-Bera (JB):                1.404
Skew:                           0.017   Prob(JB):                        0.496
Kurtosis:                       2.726   Cond. No.                         227.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [131]:
n = 15
idx = np.random.randint(data.shape[0], size=n)
x_test = data[idx, :]

In [142]:
x_test1 = sm.add_constant(x_test)
y_test = model.predict(x_test1).flatten()
print(y_test)

[128.82725506 129.05497324 149.46967223  87.66624129 138.95595037
 252.44934852 128.82725506 173.24601643 150.50918174 121.5808709
 203.75145711  95.06145678 122.53790409 117.99633487 160.41863314]


In [143]:
y_Teta = Teta.dot(x_test1.T)
print(y_Teta)

[128.82725506 129.05497324 149.46967223  87.66624129 138.95595037
 252.44934852 128.82725506 173.24601643 150.50918174 121.5808709
 203.75145711  95.06145678 122.53790409 117.99633487 160.41863314]


In [144]:
y_tg = target[idx].flatten()
print(y_tg)

[140. 131.  55. 102. 142. 245. 140. 190. 197. 113. 248.  88.  66. 160.
 262.]


In [145]:
rmse = np.sqrt(sum((y_tg - y_test) ** 2) / n)
print(rmse)

44.15979771897915


In [137]:
(max(target) - min(target)) / rmse

array([7.26905504])

In [138]:
max(target)

array([346.])

In [139]:
min(target)

array([25.])

In [140]:
np.sqrt(np.var(target))

77.00574586945044